# Generated by Django 4.2.9 on 2024-01-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_shoppingitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
