# Generated by Django 4.2.9 on 2024-02-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_shoppingitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
